CREATE DATABASE Inventario;
USE Inventario;

CREATE TABLE USUARIO (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    LastNamep VARCHAR(50) NOT NULL,
    LastNamem VARCHAR(50) NOT NULL,
    Rol VARCHAR(10) NOT NULL,
    Tel VARCHAR(12) NOT NULL,
    Email VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ENTRADA (
	ID INT NOT NULL AUTO_INCREMENT,
    FK_USUARIO INT NOT NULL,
    FECHA DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE SALIDA (
	ID INT NOT NULL AUTO_INCREMENT,
    FK_USUARIO INT NOT NULL,
    FECHA DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE UBICACION(
	ID INT NOT NULL AUTO_INCREMENT,
    CALLE VARCHAR(50) NOT NULL,
    COLONIA VARCHAR(50) NULL,
    NUM INT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PROVEEDOR(
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    RFC VARCHAR(10) NULL,
    FK_UBI INT NOT NULL,
    EMAIL VARCHAR(50) NULL,
    TEL VARCHAR(12) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(FK_UBI) REFERENCES UBICACION(ID)
);

CREATE TABLE CATEGORIA(
		ID INT NOT NULL AUTO_INCREMENT,
        PRECIO DECIMAL(10,2) NOT NULL,
        DESCR VARCHAR(100) NOT NULL,
        PRIMARY KEY (ID)
);

CREATE TABLE ARTICULO(
	ID INT NOT NULL AUTO_INCREMENT,
    FK_PROVEEDOR INT NOT NULL,
    CODIGO INT NOT NULL,
    DESCR VARCHAR(100) NULL,
    COSTO DECIMAL(10,2) NOT NULL,
    EXISTENCIA INT NOT NULL,
    FK_CATEGORIA INT NOT NULL,
    FK_USUARIO INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(FK_PROVEEDOR) REFERENCES PROVEEDOR(ID),
    FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID),
    FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID)
);